import { NgModule } from '@angular/core';
import * as Material from '@angular/material';
@NgModule({
  declarations: [],
  imports: [
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatDialogModule,
    Material.MatButtonModule,
    Material.MatExpansionModule,
    Material.MatMenuModule,
    Material.MatIconModule,
    Material.MatCheckboxModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatChipsModule,
    Material.MatAutocompleteModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatSnackBarModule,
    Material.MatSelectModule,
    Material.MatRadioModule,
    Material.MatGridListModule,
    Material.MatCardModule,
    Material.MatProgressSpinnerModule,
    Material.MatStepperModule,
  ],
  exports: [
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatDialogModule,
    Material.MatButtonModule,
    Material.MatExpansionModule,
    Material.MatMenuModule,
    Material.MatIconModule,
    Material.MatCheckboxModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatChipsModule,
    Material.MatAutocompleteModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatSnackBarModule,
    Material.MatSelectModule,
    Material.MatRadioModule,
    Material.MatGridListModule,
    Material.MatCardModule,
    Material.MatProgressSpinnerModule,
    Material.MatStepperModule,
  ],
})
export class MaterialModule {}
